<a href="https://colab.research.google.com/github/NGYIJAY-hub/data-science-toolkit/blob/main/new_notebook_tut3ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2. array 2x2

In [ ]:
import numpy as np;
b=np.array([[1,2],[3,4]]);
print(b);
print(b.shape);

[[1 2]
 [3 4]]
(2, 2)


3.

In [ ]:
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]);
print(c);
print(c.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
d=np.zeros((2,2));
print(d);
e=np.ones((2,2));
print(e);

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
np.random.seed(42);
G=np.random.rand(6,3)
print("Original Array:\n",G)

G_T=G.T
print("Transposed Array:\n",G_T)


Original Array:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]
Transposed Array:
 [[0.37454012 0.59865848 0.05808361 0.70807258 0.83244264 0.18340451]
 [0.95071431 0.15601864 0.86617615 0.02058449 0.21233911 0.30424224]
 [0.73199394 0.15599452 0.60111501 0.96990985 0.18182497 0.52475643]]


In [ ]:
n,p,m=2,3,4

K=np.random.rand(n,p)
L=np.random.rand(p,m)

print("Matrix K:\n",K)
print("Matrix L:\n",L)

#compute dot product
C=np.dot(K,L)
print("Dot Product:\n",C)

Matrix K:
 [[0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]]
Matrix L:
 [[0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]]
Dot Product:
 [[0.40932755 0.93325892 0.85400762 0.76640286]
 [0.26052213 0.47073292 0.55911498 0.4177162 ]]
